import { CandidateDeployment, WorkloadFingerprint } from "../types";

export function generateBigQueryTelemetryExport(
  candidate: CandidateDeployment,
  workload?: WorkloadFingerprint
): {
  bigquery_export_sql: string;
} {
  const safeModelId = candidate.model_id.replace(/'/g, "\\'");

  const bigquerySql = `-- Google BigQuery Telemetry Export & Analytics Schema
-- Generated by ModelForge Autonomous Inference Engine for ${candidate.model_id}

CREATE SCHEMA IF NOT EXISTS \`modelforge_telemetry\`
  OPTIONS(
    location = "US",
    description = "ModelForge Empirical Telemetry, Compute Passports, and SLO Analytics"
  );

-- Table: Inference Execution Events & Performance Metrics
CREATE TABLE IF NOT EXISTS \`modelforge_telemetry.inference_events\`
(
  event_id STRING NOT NULL,
  deployment_id STRING NOT NULL,
  model_id STRING NOT NULL,
  model_revision STRING NOT NULL,
  runtime STRING NOT NULL,
  runtime_version STRING NOT NULL,
  accelerator STRING NOT NULL,
  accelerator_vendor STRING NOT NULL,
  accelerator_count INT64 NOT NULL,
  precision STRING NOT NULL,
  prompt_tokens INT64,
  completion_tokens INT64,
  ttft_ms FLOAT64,
  tpot_ms FLOAT64,
  total_latency_ms FLOAT64,
  cost_usd FLOAT64,
  energy_joules FLOAT64,
  error_code STRING,
  is_canary BOOL,
  event_timestamp TIMESTAMP NOT NULL
)
PARTITION BY DATE(event_timestamp)
CLUSTER BY model_id, runtime, accelerator
OPTIONS(
  description = "Partitioned inference telemetry logs for real-time SLO verification",
  partition_expiration_days = 90
);

-- Analytical View: P50, P90, P95, P99 Empirical Latencies & Hourly Spend
CREATE OR REPLACE VIEW \`modelforge_telemetry.v_hourly_model_performance\` AS
SELECT
  TIMESTAMP_TRUNC(event_timestamp, HOUR) AS hour_window,
  model_id,
  runtime,
  accelerator,
  COUNT(1) AS total_requests,
  ROUND(COUNTIF(error_code IS NOT NULL) / COUNT(1) * 100, 3) AS error_rate_pct,
  ROUND(APPROX_QUANTILES(ttft_ms, 100)[OFFSET(50)], 2) AS p50_ttft_ms,
  ROUND(APPROX_QUANTILES(ttft_ms, 100)[OFFSET(90)], 2) AS p90_ttft_ms,
  ROUND(APPROX_QUANTILES(ttft_ms, 100)[OFFSET(95)], 2) AS p95_ttft_ms,
  ROUND(APPROX_QUANTILES(ttft_ms, 100)[OFFSET(99)], 2) AS p99_ttft_ms,
  ROUND(AVG(tpot_ms), 2) AS mean_tpot_ms,
  ROUND(SUM(prompt_tokens + completion_tokens) / 3600.0, 1) AS throughput_tokens_per_sec,
  ROUND(SUM(cost_usd), 4) AS total_cost_usd
FROM \`modelforge_telemetry.inference_events\`
WHERE event_timestamp >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 7 DAY)
GROUP BY hour_window, model_id, runtime, accelerator;

-- Seed initial telemetry profile based on SLO compiled targets
INSERT INTO \`modelforge_telemetry.inference_events\` (
  event_id, deployment_id, model_id, model_revision, runtime, runtime_version,
  accelerator, accelerator_vendor, accelerator_count, precision,
  prompt_tokens, completion_tokens, ttft_ms, tpot_ms, total_latency_ms,
  cost_usd, energy_joules, error_code, is_canary, event_timestamp
) VALUES (
  GENERATE_UUID(),
  'dep-compiled-${Date.now()}',
  '${safeModelId}',
  '${candidate.model_revision}',
  '${candidate.runtime}',
  '${candidate.runtime_version}',
  '${candidate.accelerator}',
  '${candidate.accelerator_vendor}',
  ${candidate.accelerator_count},
  '${candidate.precision}',
  ${workload?.prompt_token_mean ?? 2048},
  ${workload?.output_token_mean ?? 256},
  ${candidate.expected_p95_ttft_ms},
  ${candidate.expected_p50_tpot_ms},
  ${candidate.expected_p95_ttft_ms + (workload?.output_token_mean ?? 256) * candidate.expected_p50_tpot_ms},
  ${((candidate.cost_per_million_tokens_usd / 1e6) * ((workload?.prompt_token_mean ?? 2048) + (workload?.output_token_mean ?? 256))).toFixed(6)},
  ${(candidate.estimated_energy_joules_per_token ?? 0.8) * ((workload?.prompt_token_mean ?? 2048) + (workload?.output_token_mean ?? 256))},
  NULL,
  FALSE,
  CURRENT_TIMESTAMP()
);
`;

  return { bigquery_export_sql: bigquerySql };
}
