import { CandidateDeployment, WorkloadFingerprint } from "../types";

export function generateDynamoManifest(
  candidate: CandidateDeployment,
  workload: WorkloadFingerprint,
): {
  dynamo_config_yaml: string;
  env_example: string;
  deployment_notes_md: string;
} {
  const isDisaggregated = candidate.disaggregated_topology?.enabled ?? false;
  const prefillWorkers = candidate.disaggregated_topology?.prefill_workers ?? 1;
  const decodeWorkers = candidate.disaggregated_topology?.decode_workers ?? 2;

  const dynamoConfigYaml = `# NVIDIA Dynamo Serving Configuration
# Generated by ModelForge SLO Compiler v2.0.0
# Target Model: ${candidate.model_id}@${candidate.model_revision}
apiVersion: dynamo.nvidia.com/v1alpha1
kind: DynamoServingDeployment
metadata:
  name: ${candidate.model_id.toLowerCase().replace(/[^a-z0-9]/g, "-")}-dynamo
spec:
  model:
    repository: "${candidate.model_id}"
    revision: "${candidate.model_revision}"
    precision: "${candidate.precision}"
    engine: "tensorrt-llm"
  
  serving_mode: ${isDisaggregated ? "disaggregated" : "converged"}
  
  routing:
    policy: ${candidate.disaggregated_topology?.kv_routing_policy ?? "kv_cache_affinity"}
    session_stickiness: true
    cross_node_interconnect: "${candidate.disaggregated_topology?.cross_node_interconnect ?? "infiniband_ndr"}"

  topology:
    ${
      isDisaggregated
        ? `prefill:
      replicas: ${prefillWorkers}
      tensor_parallel_size: ${candidate.tensor_parallel_size}
      pipeline_parallel_size: 1
      gpu_allocation:
        device_type: "${candidate.disaggregated_topology?.prefill_gpu_type ?? candidate.accelerator}"
        count_per_replica: ${candidate.tensor_parallel_size}
      kv_cache:
        chunk_size: 128
        transfer_backend: "nvccl"
        
    decode:
      replicas: ${decodeWorkers}
      tensor_parallel_size: ${Math.max(1, Math.floor(candidate.tensor_parallel_size / 2))}
      pipeline_parallel_size: 1
      gpu_allocation:
        device_type: "${candidate.disaggregated_topology?.decode_gpu_type ?? candidate.accelerator}"
        count_per_replica: ${Math.max(1, Math.floor(candidate.tensor_parallel_size / 2))}
      batching:
        max_batch_size: ${workload.target_concurrency * 2}
        enable_chunked_prefill: true`
        : `converged:
      replicas: ${candidate.replicas}
      tensor_parallel_size: ${candidate.tensor_parallel_size}
      pipeline_parallel_size: ${candidate.pipeline_parallel_size}
      gpu_allocation:
        device_type: "${candidate.accelerator}"
        count_per_replica: ${candidate.accelerator_count}`
    }

  autoscaling:
    min_replicas: 1
    max_replicas: ${candidate.replicas * 4}
    target_metric: "p95_ttft_ms"
    target_value: 400
`;

  const envExample = `# NVIDIA Dynamo Environment Configuration
NGC_API_KEY=nvapi-your-key-here
HF_TOKEN=hf_your-huggingface-token-here
DYNAMO_ROUTER_PORT=8000
DYNAMO_METRICS_PORT=9090
DYNAMO_LOG_LEVEL=INFO
TENSORRT_LLM_ENABLE_KV_TRANSFER=1
`;

  const deploymentNotesMd = `### NVIDIA Dynamo Deployment Notes
- **Serving Architecture:** ${isDisaggregated ? "Disaggregated Prefill / Decode Topology" : "Converged Serving"}
- **Model Revision:** \`${candidate.model_id}@${candidate.model_revision}\`
- **Recommended Hardware:** ${candidate.accelerator_count}x ${candidate.accelerator} (${candidate.precision.toUpperCase()})
- **KV Routing:** KV Cache affinity ensures minimum cross-node recomputation overhead.
- **Estimated Throughput:** ${candidate.expected_throughput_tps} tok/s | P95 TTFT: ${candidate.expected_p95_ttft_ms} ms
- **Confidence Level:** ${candidate.confidence_score}/100 (${candidate.provenance})
`;

  return {
    dynamo_config_yaml: dynamoConfigYaml,
    env_example: envExample,
    deployment_notes_md: deploymentNotesMd,
  };
}
