import { CandidateDeployment, WorkloadFingerprint } from "../types";

export function generateGkeTpuManifest(
  candidate: CandidateDeployment,
  workload?: WorkloadFingerprint
): {
  gke_tpu_yaml: string;
  deployment_notes_md: string;
} {
  const safeName = candidate.model_id.toLowerCase().replace(/[^a-z0-9]/g, "-");

  // Determine TPU slice accelerator name and topology
  let tpuAccelerator = "tpu-v5p-slice";
  let topology = "2x2x1";

  if (candidate.accelerator.includes("v6e")) {
    tpuAccelerator = "tpu-v6e-slice";
    topology = candidate.accelerator_count >= 8 ? "2x2x2" : candidate.accelerator_count >= 4 ? "2x2x1" : "1x1x1";
  } else if (candidate.accelerator.includes("v5p")) {
    tpuAccelerator = "tpu-v5p-slice";
    topology = candidate.accelerator_count >= 16 ? "2x2x4" : candidate.accelerator_count >= 8 ? "2x2x2" : "2x2x1";
  } else {
    tpuAccelerator = "tpu-v5e-slice";
    topology = candidate.accelerator_count >= 8 ? "2x4" : "2x2";
  }

  const gkeTpuYaml = `# Google Kubernetes Engine (GKE) Cloud TPU Multislice Serving Deployment
# Generated by ModelForge Autonomous Inference Engine
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-tpu-${safeName}
  namespace: modelforge-serving
  labels:
    app.kubernetes.io/name: modelforge-tpu-serving
    model.modelforge.dev/id: "${safeName}"
    model.modelforge.dev/precision: "${candidate.precision}"
    model.modelforge.dev/topology: "${topology}"
spec:
  replicas: ${candidate.replicas}
  selector:
    matchLabels:
      app: gke-tpu-${safeName}
  template:
    metadata:
      labels:
        app: gke-tpu-${safeName}
      annotations:
        gke.cloud.google.com/tpu-topology: "${topology}"
    spec:
      nodeSelector:
        cloud.google.com/gke-tpu-accelerator: "${tpuAccelerator}"
        cloud.google.com/gke-tpu-topology: "${topology}"
      containers:
      - name: tpu-serving-engine
        image: vllm/vllm-tpu:v0.6.4
        args:
          - "--model"
          - "${candidate.model_id}"
          - "--revision"
          - "${candidate.model_revision}"
          - "--tensor-parallel-size"
          - "${candidate.tensor_parallel_size}"
          - "--max-model-len"
          - "${workload?.context_length_target ?? 8192}"
          - "--dtype"
          - "${candidate.precision === 'bf16' ? 'bfloat16' : 'auto'}"
        env:
          - name: PJRT_DEVICE
            value: "TPU"
          - name: TPU_CHIPS_PER_HOST_BOUNDS
            value: "${topology.replace(/x/g, ",")}"
          - name: VLLM_ENGINE_ITERATION_TIMEOUT_S
            value: "60"
        ports:
          - containerPort: 8000
            name: http-serving
        resources:
          limits:
            google.com/tpu: ${candidate.accelerator_count}
            memory: "${Math.ceil(candidate.memory_estimate_gb * 1.4)}Gi"
            cpu: "${candidate.accelerator_count * 4}"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 45
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: gke-tpu-${safeName}-svc
  namespace: modelforge-serving
spec:
  selector:
    app: gke-tpu-${safeName}
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
`;

  const deploymentNotesMd = `### GKE Cloud TPU Multislice Serving Manifest
- **Model Revision:** \`${candidate.model_id}@${candidate.model_revision}\`
- **TPU Accelerator:** \`${tpuAccelerator}\` with ICI Optical Switch Interconnect
- **Slice Topology:** \`${topology}\` (${candidate.accelerator_count} TPU chips)
- **Tensor Parallelism:** TP=${candidate.tensor_parallel_size}
- **VRAM Allocation:** ~${candidate.memory_estimate_gb.toFixed(1)} GB HBM
- **Serving Engine:** vLLM TPU Engine with PJRT runtime.
`;

  return {
    gke_tpu_yaml: gkeTpuYaml,
    deployment_notes_md: deploymentNotesMd,
  };
}
