import { CandidateDeployment, WorkloadFingerprint } from "../types";

export function generateVertexAiManifest(
  candidate: CandidateDeployment,
  _workload?: WorkloadFingerprint
): {
  vertex_ai_yaml: string;
  gcloud_deploy_sh: string;
  deployment_notes_md: string;
} {
  const safeName = candidate.model_id.toLowerCase().replace(/[^a-z0-9]/g, "-");
  const isTpu = candidate.accelerator.toLowerCase().includes("tpu");

  // Determine Google Cloud accelerator type and machine type
  let gcpAcceleratorType = "NVIDIA_TESLA_A100";
  let gcpMachineType = "a2-highgpu-1g";

  if (isTpu) {
    if (candidate.accelerator.includes("v6e")) {
      gcpAcceleratorType = "TPU_V6E";
      gcpMachineType = `ct6e-standard-${candidate.accelerator_count}t`;
    } else if (candidate.accelerator.includes("v5p")) {
      gcpAcceleratorType = "TPU_V5P";
      gcpMachineType = `ct5p-hightpu-${candidate.accelerator_count}t`;
    } else {
      gcpAcceleratorType = "TPU_V5e";
      gcpMachineType = `ct5e-standard-${candidate.accelerator_count}t`;
    }
  } else if (candidate.accelerator.includes("H100")) {
    gcpAcceleratorType = "NVIDIA_H100_80GB";
    gcpMachineType = "a3-highgpu-8g";
  } else if (candidate.accelerator.includes("L4")) {
    gcpAcceleratorType = "NVIDIA_L4";
    gcpMachineType = `g2-standard-${Math.max(4, candidate.accelerator_count * 12)}`;
  }

  const minReplicas = candidate.replicas;
  const maxReplicas = Math.max(minReplicas * 2, 4);

  const vertexAiYaml = `# Google Cloud Vertex AI Custom Service Model & Endpoint Spec
# Generated by ModelForge Autonomous Inference Engine
apiVersion: aiplatform.googleapis.com/v1
kind: Endpoint
metadata:
  name: endpoint-${safeName}
  labels:
    model.modelforge.dev/repository: "${safeName}"
    model.modelforge.dev/precision: "${candidate.precision}"
    model.modelforge.dev/runtime: "${candidate.runtime}"
spec:
  displayName: "${candidate.model_id} Production Endpoint"
  description: "SLO-compiled serving endpoint targeting ${candidate.expected_p95_ttft_ms}ms P95 TTFT"
  trafficSplit:
    deployed-candidate-${safeName}: 100
  deployedModels:
    - id: deployed-candidate-${safeName}
      displayName: "${candidate.model_id}@${candidate.model_revision}"
      model: "projects/\${PROJECT_ID}/locations/\${REGION}/models/${safeName}"
      dedicatedResources:
        machineSpec:
          machineType: "${gcpMachineType}"
          acceleratorType: "${gcpAcceleratorType}"
          acceleratorCount: ${candidate.accelerator_count}
        minReplicaCount: ${minReplicas}
        maxReplicaCount: ${maxReplicas}
        autoscalingMetricSpecs:
          - metricName: "aiplatform.googleapis.com/prediction/online/duty_cycle"
            target: 80
      enableAccessLogging: true
      enableContainerLogging: true
`;

  const gcloudDeploySh = `#!/usr/bin/env bash
# Deploy Model to Google Cloud Vertex AI Endpoint
set -euo pipefail

PROJECT_ID="\${PROJECT_ID:-\$(gcloud config get-value project)}"
REGION="\${REGION:-us-central1}"
ENDPOINT_NAME="endpoint-${safeName}"
MODEL_NAME="${safeName}"

echo "==> Creating Vertex AI Endpoint '\${ENDPOINT_NAME}' in \${REGION}..."
ENDPOINT_ID=\$(gcloud ai endpoints create \\
  --project="\${PROJECT_ID}" \\
  --region="\${REGION}" \\
  --display-name="\${ENDPOINT_NAME}" \\
  --format="value(name)")

echo "==> Deploying Model '\${MODEL_NAME}' with ${candidate.accelerator_count}x ${gcpAcceleratorType}..."
gcloud ai endpoints deploy-model "\${ENDPOINT_ID}" \\
  --project="\${PROJECT_ID}" \\
  --region="\${REGION}" \\
  --model="\${MODEL_NAME}" \\
  --display-name="${candidate.model_id}@${candidate.model_revision}" \\
  --machine-type="${gcpMachineType}" \\
  --accelerator="type=${gcpAcceleratorType},count=${candidate.accelerator_count}" \\
  --min-replica-count=${minReplicas} \\
  --max-replica-count=${maxReplicas} \\
  --traffic-split=0=100

echo "==> Vertex AI deployment active at: \${ENDPOINT_ID}"
`;

  const deploymentNotesMd = `### Google Cloud Vertex AI Serving Manifest
- **Model Revision:** \`${candidate.model_id}@${candidate.model_revision}\`
- **Target Engine:** ${candidate.target_engine}
- **Machine Specification:** \`${gcpMachineType}\` with ${candidate.accelerator_count}x \`${gcpAcceleratorType}\`
- **Target Latency (P95 TTFT):** ~${candidate.expected_p95_ttft_ms} ms
- **Projected Throughput:** ~${candidate.expected_throughput_tps.toFixed(1)} tok/s
- **Auto-Scaling:** ${minReplicas} to ${maxReplicas} instances based on 80% duty cycle.
`;

  return {
    vertex_ai_yaml: vertexAiYaml,
    gcloud_deploy_sh: gcloudDeploySh,
    deployment_notes_md: deploymentNotesMd,
  };
}
